# Generated by Django 5.0.2 on 2024-02-25 23:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="barnd",
            new_name="brand",
        ),
    ]
